CREATE OR REPLACE PACKAGE Mypk1 S
	PROCEDURE proc1(a IN NUMBER, b IN NUMBER, sum1 OUT NUMBER, avg1 OUT NUMBER, prod OUT NUMBER);
	PROCEDURE proc2(num1 IN NUMBER, result1 OUT NUMBER);
	FUNCTION fn11(num2 IN NUMBER) RETURN VARCHAR2;
	FUNCTION fn22(a IN NUMBER, b IN NUMBER, c IN NUMBER) RETURN NUMBER;
END Mypk1;

CREATE OR REPLACE PACKAGE BODY Mypk1 AS

PROCEDURE proc1(a IN NUMBER, b IN NUMBER, sum1 OUT NUMBER, avg1 OUT NUMBER, prod OUT NUMBER) IS
BEGIN
	sum1 := a+b;
	avg1 := (a+b)/2;
	prod := a*b;
END proc1;

PROCEDURE proc2(num1 IN NUMBER, result1 OUT NUMBER) IS
BEGIN
	result1 := SQRT(num1);
END proc2;

FUNCTION fn11(num2 IN NUMBER) RETURN VARCHAR2 IS
BEGIN
	IF MOD(num2,2) = 0 THEN
		RETURN 'Even';
	ELSE
		RETURN 'Odd';
	END IF;
END fn11;

FUNCTION fn22(a IN NUMBER, b IN NUMBER, c IN NUMBER) RETURN NUMBER IS
BEGIN
	RETURN a + b + c;
END fn22;
END Mypk1;








